// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL8P0CMnSJuGJ8zPVXaoz-5JTVGJ4cqSE',
    appId: '1:332461778213:web:18e91b823becd0795a66cc',
    messagingSenderId: '332461778213',
    projectId: 'my-notes-111',
    authDomain: 'my-notes-111.firebaseapp.com',
    storageBucket: 'my-notes-111.appspot.com',
    measurementId: 'G-5DH836FDC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2ALqJb2hgTRIxijel8jT1lc_VaORhfg',
    appId: '1:332461778213:android:09f64efcd9f1065a5a66cc',
    messagingSenderId: '332461778213',
    projectId: 'my-notes-111',
    storageBucket: 'my-notes-111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxrf_7XtHaehQVDC4S92Fpa0ZzNeFL57M',
    appId: '1:332461778213:ios:332ee05913e5566a5a66cc',
    messagingSenderId: '332461778213',
    projectId: 'my-notes-111',
    storageBucket: 'my-notes-111.appspot.com',
    iosClientId: '332461778213-2ennv9me0eoeg1olb28pp2unn7njlq98.apps.googleusercontent.com',
    iosBundleId: 'com.mystuff.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxrf_7XtHaehQVDC4S92Fpa0ZzNeFL57M',
    appId: '1:332461778213:ios:332ee05913e5566a5a66cc',
    messagingSenderId: '332461778213',
    projectId: 'my-notes-111',
    storageBucket: 'my-notes-111.appspot.com',
    iosClientId: '332461778213-2ennv9me0eoeg1olb28pp2unn7njlq98.apps.googleusercontent.com',
    iosBundleId: 'com.mystuff.mynotes',
  );
}
